"""ISO 639-1 language code data and validation.

Provides:
- LANGUAGES: Complete ISO 639-1 mapping of two-letter codes to native names.
- get_sorted_languages(): Returns languages sorted with English first,
  then remaining languages alphabetical by code.
- is_valid_language_code(): Validates a string against the ISO 639-1 set.
"""

# Complete ISO 639-1 mapping: code → native language name (~184 entries)
LANGUAGES: dict[str, str] = {
    "aa": "Afaraf",
    "ab": "Аҧсуа",
    "af": "Afrikaans",
    "ak": "Akan",
    "am": "አማርኛ",
    "an": "Aragonés",
    "ar": "العربية",
    "as": "অসমীয়া",
    "av": "Авар",
    "ay": "Aymar",
    "az": "Azərbaycan",
    "ba": "Башҡорт",
    "be": "Беларуская",
    "bg": "Български",
    "bh": "भोजपुरी",
    "bi": "Bislama",
    "bm": "Bamanankan",
    "bn": "বাংলা",
    "bo": "བོད་ཡིག",
    "br": "Brezhoneg",
    "bs": "Bosanski",
    "ca": "Català",
    "ce": "Нохчийн",
    "ch": "Chamoru",
    "co": "Corsu",
    "cr": "ᓀᐦᐃᔭᐍᐏᐣ",
    "cs": "Čeština",
    "cu": "Словѣньскъ",
    "cv": "Чӑваш",
    "cy": "Cymraeg",
    "da": "Dansk",
    "de": "Deutsch",
    "dv": "ދިވެހި",
    "dz": "རྫོང་ཁ",
    "ee": "Eʋegbe",  # noqa: RUF001
    "el": "Ελληνικά",
    "en": "English",
    "eo": "Esperanto",
    "es": "Español",
    "et": "Eesti",
    "eu": "Euskara",
    "fa": "فارسی",
    "ff": "Fulfulde",
    "fi": "Suomi",
    "fj": "Vosa Vakaviti",
    "fo": "Føroyskt",
    "fr": "Français",
    "fy": "Frysk",
    "ga": "Gaeilge",
    "gd": "Gàidhlig",
    "gl": "Galego",
    "gn": "Avañe'ẽ",
    "gu": "ગુજરાતી",
    "gv": "Gaelg",
    "ha": "Hausa",
    "he": "עברית",
    "hi": "हिन्दी",
    "ho": "Hiri Motu",
    "hr": "Hrvatski",
    "ht": "Kreyòl Ayisyen",
    "hu": "Magyar",
    "hy": "Հայերեն",
    "hz": "Otjiherero",
    "ia": "Interlingua",
    "id": "Bahasa Indonesia",
    "ie": "Interlingue",
    "ig": "Igbo",
    "ii": "ꆈꌠꉙ",
    "ik": "Iñupiaq",
    "io": "Ido",
    "is": "Íslenska",
    "it": "Italiano",
    "iu": "ᐃᓄᒃᑎᑐᑦ",
    "ja": "日本語",
    "jv": "Basa Jawa",
    "ka": "ქართული",
    "kg": "Kikongo",
    "ki": "Gĩkũyũ",
    "kj": "Kuanyama",
    "kk": "Қазақша",
    "kl": "Kalaallisut",
    "km": "ខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ko": "한국어",
    "kr": "Kanuri",
    "ks": "कश्मीरी",
    "ku": "Kurdî",
    "kv": "Коми",
    "kw": "Kernewek",
    "ky": "Кыргызча",
    "la": "Latina",
    "lb": "Lëtzebuergesch",
    "lg": "Luganda",
    "li": "Limburgs",
    "ln": "Lingála",
    "lo": "ລາວ",
    "lt": "Lietuvių",
    "lu": "Kiluba",
    "lv": "Latviešu",
    "mg": "Malagasy",
    "mh": "Kajin M̧ajeļ",
    "mi": "Te Reo Māori",
    "mk": "Македонски",
    "ml": "മലയാളം",
    "mn": "Монгол",
    "mr": "मराठी",
    "ms": "Bahasa Melayu",
    "mt": "Malti",
    "my": "ဗမာစာ",
    "na": "Dorerin Naoero",
    "nb": "Norsk Bokmål",
    "nd": "isiNdebele",
    "ne": "नेपाली",
    "ng": "Owambo",
    "nl": "Nederlands",
    "nn": "Norsk Nynorsk",
    "no": "Norsk",
    "nr": "isiNdebele",
    "nv": "Diné Bizaad",
    "ny": "Chichewa",
    "oc": "Occitan",
    "oj": "ᐊᓂᔑᓈᐯᒧᐎᓐ",
    "om": "Afaan Oromoo",
    "or": "ଓଡ଼ିଆ",
    "os": "Ирон",
    "pa": "ਪੰਜਾਬੀ",
    "pi": "पालि",
    "pl": "Polski",
    "ps": "پښتو",
    "pt": "Português",
    "qu": "Runa Simi",
    "rm": "Rumantsch",
    "rn": "Ikirundi",
    "ro": "Română",
    "ru": "Русский",
    "rw": "Ikinyarwanda",
    "sa": "संस्कृतम्",
    "sc": "Sardu",
    "sd": "سنڌي",
    "se": "Davvisámegiella",
    "sg": "Sängö",
    "si": "සිංහල",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sm": "Gagana Sāmoa",
    "sn": "ChiShona",
    "so": "Soomaaliga",
    "sq": "Shqip",
    "sr": "Српски",
    "ss": "SiSwati",
    "st": "Sesotho",
    "su": "Basa Sunda",
    "sv": "Svenska",
    "sw": "Kiswahili",
    "ta": "தமிழ்",
    "te": "తెలుగు",
    "tg": "Тоҷикӣ",
    "th": "ไทย",
    "ti": "ትግርኛ",
    "tk": "Türkmen",
    "tl": "Tagalog",
    "tn": "Setswana",
    "to": "Lea Faka-Tonga",
    "tr": "Türkçe",
    "ts": "Xitsonga",
    "tt": "Татарча",
    "tw": "Twi",
    "ty": "Reo Tahiti",
    "ug": "ئۇيغۇرچە",
    "uk": "Українська",
    "ur": "اردو",
    "uz": "Oʻzbek",  # noqa: RUF001
    "ve": "Tshivenḓa",
    "vi": "Tiếng Việt",
    "vo": "Volapük",
    "wa": "Walon",
    "wo": "Wolof",
    "xh": "isiXhosa",
    "yi": "ייִדיש",
    "yo": "Yorùbá",
    "za": "Saɯ Cueŋƅ",  # noqa: RUF001
    "zh": "中文",
    "zu": "isiZulu",
}


def get_sorted_languages() -> list[tuple[str, str]]:
    """Return ISO 639-1 languages sorted: English first, rest alphabetical by code.

    Returns:
        List of (code, native_name) tuples.
    """
    rest = sorted(
        ((code, name) for code, name in LANGUAGES.items() if code != "en"),
        key=lambda item: item[0],
    )
    return [("en", LANGUAGES["en"]), *rest]


def is_valid_language_code(code: str) -> bool:
    """Check whether a string is a valid ISO 639-1 language code.

    Args:
        code: The string to validate.

    Returns:
        True if the code is in the ISO 639-1 set.
    """
    return code in LANGUAGES
