"""API layer - Litestar controllers and schemas."""

from zondarr.api.health import HealthController
from zondarr.api.logs import LogController
from zondarr.api.providers import ProviderController
from zondarr.api.schemas import (
    AuthFieldInfo,
    AuthMethodsResponse,
    ConnectionTestRequest,
    ConnectionTestResponse,
    ErrorResponse,
    ExternalLoginRequest,
    FieldError,
    HealthCheckResponse,
    IdentityCreate,
    IdentityResponse,
    IdentityUpdate,
    IdentityWithUsersResponse,
    InvitationCreate,
    InvitationDetailResponse,
    InvitationResponse,
    InvitationUpdate,
    LibraryResponse,
    LibrarySyncResult,
    LivenessResponse,
    MediaServerCreate,
    MediaServerDetailResponse,
    MediaServerResponse,
    MediaServerUpdate,
    MediaServerWithLibrariesResponse,
    ProviderAuthInfo,
    ProviderMetadataResponse,
    ReadinessResponse,
    ServerSyncStatusResponse,
    SyncChannelStatusResponse,
    SyncRequest,
    SyncResult,
    UserResponse,
    ValidationErrorResponse,
)

__all__ = [
    "AuthFieldInfo",
    "AuthMethodsResponse",
    "ConnectionTestRequest",
    "ConnectionTestResponse",
    "ErrorResponse",
    "ExternalLoginRequest",
    "FieldError",
    "HealthCheckResponse",
    "HealthController",
    "IdentityCreate",
    "IdentityResponse",
    "IdentityUpdate",
    "IdentityWithUsersResponse",
    "InvitationCreate",
    "InvitationDetailResponse",
    "InvitationResponse",
    "InvitationUpdate",
    "LibraryResponse",
    "LibrarySyncResult",
    "LivenessResponse",
    "LogController",
    "MediaServerCreate",
    "MediaServerDetailResponse",
    "MediaServerResponse",
    "MediaServerUpdate",
    "MediaServerWithLibrariesResponse",
    "ProviderAuthInfo",
    "ProviderController",
    "ProviderMetadataResponse",
    "ReadinessResponse",
    "ServerSyncStatusResponse",
    "SyncChannelStatusResponse",
    "SyncRequest",
    "SyncResult",
    "UserResponse",
    "ValidationErrorResponse",
]
