"""add_unique_constraint_username_media_server

Revision ID: 667cc4e528d3
Revises: f28e9381c2ea
Create Date: 2026-03-09 20:50:31.044896
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# Revision identifiers, used by Alembic.
revision: str = "667cc4e528d3"
down_revision: str | None = "f28e9381c2ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_users_username_server", ["username", "media_server_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_username_server", type_="unique")

    # ### end Alembic commands ###
