"""add oauth_sessions table

Revision ID: 3a3f41a6c5ed
Revises: 0bd7d521e15f
Create Date: 2026-03-08 02:05:28.216566
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "3a3f41a6c5ed"
down_revision: str | None = "0bd7d521e15f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_sessions",
        sa.Column("handle", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("pin_id", sa.Integer(), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=False),
        sa.Column("auth_token", sa.String(length=512), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("redemption_token", sa.String(length=64), nullable=True),
        sa.Column("redeemed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_sessions_handle"), ["handle"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_sessions_redemption_token"),
            ["redemption_token"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_sessions_redemption_token"))
        batch_op.drop_index(batch_op.f("ix_oauth_sessions_handle"))

    op.drop_table("oauth_sessions")
    # ### end Alembic commands ###
